<?php
namespace app\admin\controller;
use think\Controller;
class BaseController  extends  Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if (!session('?userinfo')) {
            $this->redirect('free/login');
        }

    }
    public function _empty($name)
    {
        // 方法不存在   我回一直在
    }

}

