<?php

namespace app\home\model;

use think\Model;

class Member extends Model
{
    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        self::event('before_insert', function ($user) {
            $user->pwd = md5($user->pwd);
            $user->add_ip  = $_SERVER['REMOTE_ADDR'];  //获取客户端ip地址
            $user->add_time  =time();
        });
    }
    protected $pk = 'member_id';
    public function checkMember($username, $password)
    {
        $UserInfo = [
            'phone' => $username,
            'pwd' => md5($password),
        ];
        $user = $this->where($UserInfo)->find();
        if ($user) {
            unset($user['pwd']);
            session('member', $user);
            return true;
        } else {
            $this->error = '用户名错误';
            return false;
        }
    }
}
