<?php

namespace app\home\controller;

use think\Controller;
use think\Request;

class BaseController extends Controller
{
     protected function initialize()
     {
         parent::initialize(); // TODO: Change the autogenerated stub
         if (!session('?member')){
             $this->redirect('home/free/login');
         }
     }
}
