<?php

namespace app\home\controller;

use app\admin\model\Column;

use think\Controller;
use think\Db;
use think\Request;

class CommonController extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $column = Db::name('Column')->where('w_column.is_show_nav in(2,3,4)')
            ->leftJoin(' w_content_module', 'w_column.module_id=w_content_module.module_id')->select();
        $alias = ['column_name' => 'title', 'column_parent' => 'pid', 'column_id' => 'id', 'control' => 'control', 'method' => 'method', 'module_id' => "module_id"];
        $column = tree($column, 'column_id', $alias);
        $this->assign('column', $column);
        $friend_link = Db::name('friend_link')->select();
        $this->assign('friend_link', $friend_link);
        $this->bindSuperior();

    }

    /**
     * 绑定上级
     */
    public function bindSuperior(){
        $info = \request()->param();
        if (isset($info['tg'])){
            session("subordinate_member_id",$info['tg']);
        }
    }


}
